### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by korang** [sailay1996/PrintNightmare-LPE#1]
![Untitled](https://user-images.githubusercontent.com/1591010/124532801-3580a180-dddf-11eb-8b5c-f2d941776f80.jpg)

Edition	Windows 10 Pro
Version	21H1
Installed on	‎3/‎22/‎2021
OS build	19043.1081
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by sailay1996** [comment]
Printnightmare-lpe.exe, vlib.dll, xconsole.exe , put it those 3 files in the same folder. And then run Printnightmare-lpe.exe (restart the spooler service before you run for sure that normally it doesn't need)  . I guess it's not sure to work if you're in latest updated version of windows.
